version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "itsmartha-stack"
s3_prefix = "itsmartha-stack"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"production\""
image_repositories = []